# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V56SVnZzscTVdEa0yXIHqcozxWna8QyW
"""

# ===========================================
# Dog vs Cat Image Classification using CNN
# ===========================================

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras import layers, models

# -------------------------------------------
# Load Dataset
# -------------------------------------------

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()

# CIFAR-10 labels
class_names = [
    'airplane', 'automobile', 'bird', 'cat',
    'deer', 'dog', 'frog', 'horse',
    'ship', 'truck'
]

# Keep only Cats (3) and Dogs (5)

train_filter = np.where((train_labels == 3) | (train_labels == 5))[0]
test_filter = np.where((test_labels == 3) | (test_labels == 5))[0]

train_images = train_images[train_filter]
train_labels = train_labels[train_filter]

test_images = test_images[test_filter]
test_labels = test_labels[test_filter]

# Convert labels
# Cat = 0
# Dog = 1

train_labels = (train_labels == 5).astype(int)
test_labels = (test_labels == 5).astype(int)

# Normalize images

train_images = train_images / 255.0
test_images = test_images / 255.0

print("Training Images:", train_images.shape)
print("Testing Images :", test_images.shape)

# -------------------------------------------
# Display Sample Images
# -------------------------------------------

plt.figure(figsize=(10,5))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(train_images[i])

    if train_labels[i]==0:
        plt.title("Cat")
    else:
        plt.title("Dog")

    plt.axis("off")

plt.show()

# -------------------------------------------
# Build CNN Model
# -------------------------------------------

model = models.Sequential()

model.add(layers.Conv2D(
    32,
    (3,3),
    activation='relu',
    input_shape=(32,32,3)
))

model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(
    64,
    (3,3),
    activation='relu'
))

model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(
    64,
    (3,3),
    activation='relu'
))

model.add(layers.Flatten())

model.add(layers.Dense(
    64,
    activation='relu'
))

model.add(layers.Dense(
    1,
    activation='sigmoid'
))

# -------------------------------------------
# Compile Model
# -------------------------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# -------------------------------------------
# Train Model
# -------------------------------------------

history = model.fit(
    train_images,
    train_labels,
    epochs=10,
    validation_data=(test_images, test_labels)
)

# -------------------------------------------
# Evaluate Model
# -------------------------------------------

loss, accuracy = model.evaluate(test_images, test_labels)

print("\nTest Accuracy:", accuracy)

# -------------------------------------------
# Save Model
# -------------------------------------------

model.save("dog_cat_cnn_model.h5")

print("\nModel Saved Successfully!")

# -------------------------------------------
# Predict One Image
# -------------------------------------------

index = 20

image = test_images[index]

prediction = model.predict(np.expand_dims(image, axis=0))

plt.imshow(image)

if prediction[0][0] > 0.5:
    plt.title("Predicted : Dog")
else:
    plt.title("Predicted : Cat")

plt.axis("off")
plt.show()

print("Prediction Score:", prediction[0][0])